import assert from 'node:assert/strict';
import { test } from 'node:test';
import { equityHours,paperTradingWindow,type PaperTradingHours } from '../src/paper/trading-hours.js';
import { advancePaper } from '../src/paper/engine.js';
import { readFileSync } from 'node:fs';
const policy:PaperTradingHours={kind:'us_equity_off_hours_v1',entryCutoffSeconds:1800,exitLeadSeconds:600};
test('off-hours boundaries, buffers, holidays, unsupported years, and DST',()=>{
 for(const [at,regime] of [['2026-09-11T13:30:00Z','regular'],['2026-09-11T20:00:00Z','afterhours'],['2026-09-12T03:00:00Z','overnight'],['2026-09-12T04:00:00Z','weekend'],['2026-09-07T14:00:00Z','holiday'],['2026-11-27T18:00:00Z','afterhours'],['2027-01-02T14:00:00Z','calendar_unavailable']])assert.equal(equityHours(at!).regime,regime);
 assert.equal(paperTradingWindow('2026-09-11T07:29:59Z',policy).entryAllowed,true);
 assert.equal(paperTradingWindow('2026-09-11T07:30:00Z',policy).entryAllowed,false);
 assert.equal(paperTradingWindow('2026-09-11T07:49:59Z',policy).exitRequired,false);
 assert.equal(paperTradingWindow('2026-09-11T07:50:00Z',policy).exitRequired,true);
 assert.equal(paperTradingWindow('2026-09-11T08:00:00Z',policy).entryAllowed,false);
 assert.equal(paperTradingWindow('2026-09-12T12:00:00Z',policy).excludedAt,'2026-09-14T08:00:00.000Z');
 assert.equal(paperTradingWindow('2026-09-06T12:00:00Z',policy).excludedAt,'2026-09-07T04:00:00.000Z');
 assert.equal(paperTradingWindow('2026-10-31T12:00:00Z',policy).excludedAt,'2026-11-02T09:00:00.000Z');
 assert.equal(paperTradingWindow('bad',policy).entryAllowed,false);
});
test('scheduled cash exit is generated by the paper engine before excluded hours',()=>{
 const f=JSON.parse(readFileSync(new URL('./fixtures/paper-state-rejected-exit-recovery.json',import.meta.url),'utf8'));
 const at='2026-09-11T07:50:00.000Z',prior=structuredClone(f.previous);
 prior.status='open';prior.pendingSince=null;delete prior.holding;
 prior.last.blockTimestamp='2026-09-11T07:49:00.000Z';prior.last.capturedAt=prior.last.blockTimestamp;
 prior.position.enteredAt='2026-09-11T07:00:00.000Z';
 const input={...f.input,now:at,entryReasons:[],holdingChainReady:true,checkpoint:{...f.input.checkpoint,blockTimestamp:at,capturedAt:at},execution:{available:true}};
 const p={...f.session.policy,tradingHours:policy,inventoryExitPpm:1000000};delete p.holdingPolicy;
 const out=advancePaper(prior,p,input);
 assert.equal(out.action,'signal_exit');assert(out.reasons.includes('paper_scheduled_cash_exit'));
});
