import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const base = process.env.DASHBOARD_AUDIT_URL ?? 'http://127.0.0.1:4173';
const out = new URL('./', import.meta.url);
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector('#connection-label').textContent === 'Dashboard connected');
  const data = await (await page.request.get(`${base}/api/dashboard`)).json();
  assert.equal(data.focus.executionEnabled, false);
  assert.equal(data.focus.historySource, 'hypersync');
  assert.equal(data.focus.fullAccountingEnabled, false);
  assert.match(await page.locator('#focus-rehearsal').innerText(), /local fork/);
  assert.match(await page.locator('#nft-empty').innerText(), /not a live wallet position/);
  assert.equal(await page.locator('#nft-body tr').count(), data.trackedNftPositions.length);
  assert.equal(await page.locator('#research-details').getAttribute('open'), null);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: new URL('desktop.png', out).pathname, fullPage: true });
  await page.locator('#research-details > summary').click();
  assert.match(await page.locator('#policy-replay-date').innerText(), /2026-09-04/);
  assert.match(await page.locator('#accounting-status-note').innerText(), /paused intentionally/);
  assert.equal(await page.locator('#policy-replay-body tr').count(), data.rangePolicyReplay.candidates.length);
  await page.locator('#research-details > summary').click();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: new URL('mobile.png', out).pathname, fullPage: true });

  const stale = structuredClone(data);
  stale.overview.indexer.updatedAt = '2026-09-01T00:00:00.000Z';
  stale.overview.replay.updatedAt = '2026-09-01T00:00:00.000Z';
  stale.focus.checkpoint.capturedAt = '2026-09-01T00:00:00.000Z';
  stale.focus.checkpoint.blockTimestamp = '2026-09-01T00:00:00.000Z';
  stale.focus.checkpoint.status = 'valid';
  stale.riskAssets[0].oraclePaused = null;
  stale.riskAssets[0].corporateActionPending = null;
  await page.route('**/api/dashboard', route => route.fulfill({ json: stale }));
  await page.evaluate(() => refresh());
  assert.equal(await page.locator('#focus-index').innerText(), 'Stale or missing');
  assert.equal(await page.locator('#focus-checkpoint').innerText(), 'Stale');
  assert.match(await page.locator('#focus-reference-note').innerText(), /diagnostic/);
  assert.match(await page.locator('#risk-body tr').first().textContent(), /Unknown.*Unknown/);
  await page.unroute('**/api/dashboard');
  await page.route('**/api/dashboard', route => route.fulfill({ status: 500, json: { error: 'audit_fixture_failure' } }));
  await page.evaluate(() => refresh());
  assert.equal(await page.locator('#connection-label').innerText(), 'Data unavailable');
  assert.match(await page.locator('#error-banner').innerText(), /no longer current/);
  await page.unroute('**/api/dashboard');
  await page.route('**/api/dashboard', route => route.fulfill({ json: { ...data, focus: { ...data.focus, checkpoint: null, rehearsal: null, lastPlan: null } } }));
  await page.evaluate(() => refresh());
  assert.equal(await page.locator('#focus-checkpoint').innerText(), 'Missing');
  assert.equal(await page.locator('#focus-rehearsal').innerText(), 'Evidence unavailable');
  assert.equal(await page.locator('#focus-spot').innerText(), 'Unavailable');
  assert.deepEqual(errors, []);
  const evidence = { observedAt: data.overview.serverTime, focus: data.focus, overview: data.overview, trackedNftCount: data.trackedNftPositions.length, checks: ['desktop and mobile render without horizontal overflow', 'research collapsed and historical dates visible when expanded', 'local rehearsal separated from mainnet NFT records', 'paused full accounting shown explicitly', 'stopped matching cursors and old checkpoint marked stale', 'unknown pause and corporate action flags remain unknown', 'API failure marks previous response as no longer current', 'missing checkpoint and rehearsal do not retain previous values', 'no browser page errors'] };
  await writeFile(new URL('after.json', out), JSON.stringify(evidence, null, 2) + '\n');
  console.log(JSON.stringify({ observedAt: evidence.observedAt, checks: evidence.checks, pageErrors: errors }));
} finally { await browser.close(); }
