import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const base = process.env.DASHBOARD_AUDIT_URL ?? 'http://127.0.0.1:4173';
const out = new URL('./',import.meta.url);
const browser = await chromium.launch({headless:true});
try {
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.waitForFunction(()=>document.querySelector('#connection-label').textContent==='Dashboard connected');
 const data=await (await page.request.get(`${base}/api/dashboard`)).json();
 assert.equal(data.paper.executionEligible,false);
 assert.equal(data.paper.policy.mode,'guarded');
 assert.equal(data.paper.state.status,'waiting');
 assert.equal(data.paper.state.pnlQuote,null);
 assert.match(await page.locator('#paper-status').innerText(),/Session #1.*Waiting/);
 assert.equal(await page.locator('#paper-pnl').innerText(),'—');
 assert.match(await page.locator('#paper-nav').innerText(),/1,000 USDG/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#paper-panel').screenshot({path:new URL('live-desktop.png',out).pathname});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#paper-panel').screenshot({path:new URL('live-mobile.png',out).pathname});
 const fixture=structuredClone(data);
 fixture.paper.id='UI fixture';
 fixture.paper.state={...fixture.paper.state,status:'open',navQuote:'1002000000',holdQuote:'1001000000',pnlQuote:'2000000',alphaQuote:'1000000',feeValueQuote:'5000000',costsPaidQuote:'2000000',exitReserveQuote:'1000000',maxDrawdownPpm:'3000',intervals:2,observedSwaps:'10',position:{tickLower:221600,tickUpper:222000}};
 fixture.paper.points=[0,1,2].map(i=>({checkpointId:String(i),block:String(100+i),observedAt:new Date(Date.parse(data.overview.serverTime)-(2-i)*300000).toISOString(),sourceAt:new Date(Date.parse(data.overview.serverTime)-(2-i)*300000).toISOString(),action:i?'mark':'enter',navQuote:String(997000000+i*2500000),holdQuote:String(998000000+i*1500000),pnlQuote:String(-3000000+i*2500000),alphaQuote:String(-1000000+i*1000000),reasons:[]}));
 await page.route('**/api/dashboard',route=>route.fulfill({json:fixture}));
 await page.evaluate(()=>refresh());
 assert.equal(await page.locator('#paper-pnl').innerText(),'2 USDG');
 assert.equal(await page.locator('#paper-alpha').innerText(),'1 USDG');
 assert.equal(await page.locator('#paper-chart polyline').count(),2);
 assert.equal(await page.locator('#paper-chart circle').count(),6);
 assert.equal(await page.locator('#paper-journal tr').count(),3);
 await page.unroute('**/api/dashboard');
 fixture.paper.state.status='invalid'; fixture.paper.state.navQuote=null;fixture.paper.state.pnlQuote=null;fixture.paper.state.alphaQuote=null;fixture.paper.state.feeValueQuote=null;
 await page.route('**/api/dashboard',route=>route.fulfill({json:fixture}));
 await page.evaluate(()=>refresh());
 assert.equal(await page.locator('#paper-chart polyline').count(),0);
 assert.equal(await page.locator('#paper-pnl').innerText(),'—');
 assert.match(await page.locator('#paper-chart-empty').innerText(),/coverage is incomplete/);
 await page.unroute('**/api/dashboard');
 await page.route('**/api/dashboard',route=>route.fulfill({json:{...data,paper:null}}));
 await page.evaluate(()=>refresh());
 assert.equal(await page.locator('#paper-nav').innerText(),'—');
 assert.equal(await page.locator('#paper-journal tr').count(),0);
 assert.match(await page.locator('#paper-status').innerText(),/No paper session/);
 assert.deepEqual(errors,[]);
 await writeFile(new URL('live-snapshot.json',out),JSON.stringify({observedAt:data.overview.serverTime,paper:data.paper,checks:['real waiting session has no invented PnL','desktop and mobile have no page overflow','synthetic chart renders net value and passive holdings','invalid coverage hides performance curve and PnL','missing session clears prior values','no browser errors'],fixtureProfitsStored:false},null,2)+'\n');
 console.log(JSON.stringify({observedAt:data.overview.serverTime,state:data.paper.state.status,observations:data.paper.points.length,checksPassed:true,pageErrors:errors}));
} finally {await browser.close();}
